# SAFE MINIMAL NIXPACKS CONFIGURATION
# This avoids the ca-certificates error by using minimal packages

[start]
cmd = "gunicorn main:app --bind 0.0.0.0:$PORT --workers 2 --timeout 120 --max-requests 1000"

[phases.setup]
nixPkgs = ["python312"]

[phases.install]
cmds = [
    "pip install --upgrade pip",
    "pip install -r requirements.txt",
    "seleniumbase install chromium --path"
]

# REMOVED PROBLEMATIC PACKAGES:
# - ca-certificates (doesn't exist, should be cacert)
# - chromium/chromedriver (let seleniumbase handle it)
# - gtk3, glib, etc (not needed for headless operation)
#
# BENEFITS:
# - Avoids package name errors
# - Faster builds
# - Less memory usage
# - Better compatibility
