[start]
cmd = "python main.py"

[phases.build]
dependsOn = ["install"]

[phases.install]
dependsOn = ["setup"]
cmds = [
    "pip install --upgrade pip setuptools wheel",
    "pip install -r requirements.txt",
    "seleniumbase install chromium",
    "seleniumbase install chromedriver",
    "python -c 'import seleniumbase; print(\"SeleniumBase installed successfully\")'",
    "python -c 'from seleniumbase import SB; print(\"SB import successful\")'",
    "which chromium || which google-chrome || echo 'Chrome installation check'",
    "which chromedriver || echo 'ChromeDriver installation check'"
]

[phases.setup]
nixPkgs = [
    "python312",
    "python312Packages.pip",
    "python312Packages.setuptools",
    "python312Packages.wheel",
    "chromium",
    "chromedriver",
    "xvfb-run",
    "fontconfig",
    "freetype",
    "glib",
    "gtk3",
    "harfbuzz",
    "icu",
    "libdrm",
    "libjpeg",
    "libpng",
    "libtiff",
    "libwebp",
    "mesa",
    "nspr",
    "nss",
    "pango",
    "zlib",
    "libgcc",
    "glibc",
    "gcc",
    "openssl",
    "ca-certificates"
]

[variables]
CHROME_BINARY_LOCATION = "/nix/store/*/bin/chromium"
CHROMEDRIVER_PATH = "/nix/store/*/bin/chromedriver"
