[start]
cmd = "gunicorn main:app --bind 0.0.0.0:$PORT --workers 2 --timeout 120"

[phases.build]
dependsOn = ["install"]

[phases.install]
dependsOn = ["setup"]
cmds = [
    "pip install --upgrade pip setuptools wheel",
    "pip install -r requirements.txt"
]

[phases.setup]
nixPkgs = [
    "python312",
    "python312Packages.pip",
    "python312Packages.setuptools",
    "python312Packages.wheel"
]

[variables]
PYTHONUNBUFFERED = "1"
