[start]
cmd = "gunicorn main:app --bind 0.0.0.0:$PORT --workers 1 --timeout 300"

[phases.build]
dependsOn = ["install"]

[phases.install]
dependsOn = ["setup"]
cmds = [
    "pip install --upgrade pip setuptools wheel",
    "pip install -r requirements.txt",
    "seleniumbase install chromium",
    "seleniumbase install chromedriver",
    "python -c 'import seleniumbase; print(\"SeleniumBase installed successfully\")'",
    "python -c 'from seleniumbase import SB; print(\"SB import successful\")'",
    "python -c 'from python2captcha import TwoCaptcha; print(\"2Captcha library installed successfully\")'",
    "which chromium || which google-chrome || echo 'Chrome installation check'",
    "which chromedriver || echo 'ChromeDriver installation check'"
]

[phases.setup]
nixPkgs = [
    "python312",
    "python312Packages.pip", 
    "python312Packages.setuptools",
    "python312Packages.wheel",
    "chromium",
    "chromedriver"
]

[variables]
PYTHONUNBUFFERED = "1"
RAILWAY_ENVIRONMENT = "production"
