[build]
builder = "NIXPACKS"

[deploy]
startCommand = "gunicorn main:app --bind 0.0.0.0:$PORT --workers 1 --timeout 300 --max-requests 1000 --preload"
healthcheckPath = "/health"
healthcheckTimeout = 60
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5

[env]
PYTHONUNBUFFERED = "1"
RAILWAY_ENVIRONMENT = "production"
PORT = "5000"
